(function () {
    /* commonData*/
    ez = window.createNamespace("ez");
    ez.data = window.createNamespace("ez.data");
    ez.data.defaultOption = {
        "urlBase": "#/home",
        "imageUrlBase": "./resource/image/category",
		"unit":"mm"
    }

    /* products */
    var productData =[
{	popular : 'TRUE',	productId : 'erjop01',	productName : 'Oil painting-nature',	categoryId : '1',	length : 'customize',	width : 'customize',	effectId : '3',	materialId : '3',		categoryName : 'wall hangings',	effectName : 'Genuine Oil painting',	materialName : 'canvas',	applicationIdList : [1,2,3],	applicationList : ['Bedroom','living room','study room'],	},
{	popular : '',	productId : 'erjop02',	productName : 'oil painting-portraits',	categoryId : '1',	length : 'customize',	width : 'customize',	effectId : '3',	materialId : '3',		categoryName : 'wall hangings',	effectName : 'Genuine Oil painting',	materialName : 'canvas',	applicationIdList : [1,2,3],	applicationList : ['Bedroom','living room','study room'],	},
{	popular : '',	productId : 'erjdi01',	productName : 'Digital inkjet-nature',	categoryId : '1',	length : 'customize',	width : 'customize',	effectId : '4',	materialId : '3',		categoryName : 'wall hangings',	effectName : 'Digital printing',	materialName : 'canvas',	applicationIdList : [1,2,3],	applicationList : ['Bedroom','living room','study room'],	},
{	popular : '',	productId : 'erjdi02',	productName : 'Digital inkjet-portraits',	categoryId : '1',	length : 'customize',	width : 'customize',	effectId : '4',	materialId : '3',		categoryName : 'wall hangings',	effectName : 'Digital printing',	materialName : 'canvas',	applicationIdList : [1,2,3],	applicationList : ['Bedroom','living room','study room'],	},
{	popular : '',	productId : 'erwabc1038',	productName : 'Growth chart-The Little Red Riding-hood',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,5],	applicationList : ['Bedroom','Nursery room'],	},
{	popular : '',	productId : 'erwabc1003',	productName : 'Growth chart-Elephants',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,5],	applicationList : ['Bedroom','Nursery room'],	},
{	popular : '',	productId : 'erwd8268',	productName : 'coffe cup and beams-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,4],	applicationList : ['living room','dinning room'],	},
{	popular : 'TRUE',	productId : 'erwd01',	productName : 'Elephant and rabbits wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [5],	applicationList : ['Nursery room'],	},
{	popular : '',	productId : 'erwjm7225',	productName : 'world trip-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,2,3],	applicationList : ['Bedroom','living room','study room'],	},
{	popular : '',	productId : 'erwabc603',	productName : 'snow princess-wall stickers ',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [5],	applicationList : ['Nursery room'],	},
{	popular : '',	productId : 'erwabc1009',	productName : 'panda, tiger-wall stickers ',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [5],	applicationList : ['Nursery room'],	},
{	popular : '',	productId : 'erwabc1004',	productName : 'purple flower-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,5],	applicationList : ['living room','Nursery room'],	},
{	popular : '',	productId : 'erwabc1013',	productName : 'light bulb-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,3],	applicationList : ['living room','study room'],	},
{	popular : '',	productId : 'erwabc1001',	productName : 'cartoon world map-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,5],	applicationList : ['living room','Nursery room'],	},
{	popular : '',	productId : 'erwabc1033',	productName : 'deer and tiger- wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [5],	applicationList : ['Nursery room'],	},
{	popular : '',	productId : 'erwjm8052',	productName : 'butterfly-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2],	applicationList : ['living room'],	},
{	popular : '',	productId : 'erwjm8347',	productName : 'bicycle and heart-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2],	applicationList : ['living room'],	},
{	popular : '',	productId : 'erwjm8212',	productName : 'tree and leaves-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2],	applicationList : ['living room'],	},
{	popular : '',	productId : 'erwjm9002',	productName : 'maple leaves-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2],	applicationList : ['living room'],	},
{	popular : '',	productId : 'erwjm8329',	productName : 'violinist-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm8394',	productName : 'dandelion and love-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm8320',	productName : 'good day hanger-wall sitckers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm8346',	productName : 'travel sydney-wall stickers',	categoryId : '2',	length : '50',	width : '70',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm7092',	productName : 'travel paris-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm7115',	productName : 'bushes and butteryfly-wall sitckers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm7231',	productName : 'travel pisa-wall sitckers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm7257',	productName : 'palm tree and monkeys-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,5,6],	applicationList : ['living room','Nursery room','commerical area'],	},
{	popular : '',	productId : 'erwjm7261',	productName : 'Growth chart-tree',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,2,5,6],	applicationList : ['Bedroom','living room','Nursery room','commerical area'],	},
{	popular : '',	productId : 'erwjm7278',	productName : 'elephant and trees-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm7279',	productName : 'travel london-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,2,6],	applicationList : ['Bedroom','living room','commerical area'],	},
{	popular : '',	productId : 'erwjm7280',	productName : 'travel dubai-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,2,6],	applicationList : ['Bedroom','living room','commerical area'],	},
{	popular : '',	productId : 'erwjm201-230',	productName : 'letter on the wall-stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [2,6],	applicationList : ['living room','commerical area'],	},
{	popular : '',	productId : 'erwjm601-629',	productName : 'letters-wall stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,3],	applicationList : ['Bedroom','study room'],	},
{	popular : '',	productId : 'erwjm301',	productName : 'reminder on the wall-stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,3],	applicationList : ['Bedroom','study room'],	},
{	popular : 'TRUE',	productId : 'erwjcd801',	productName : 'clock on the wall-stickers',	categoryId : '2',	length : '60',	width : '90',	effectId : '',	materialId : '2',		categoryName : 'wall decals',	effectName : '',	materialName : 'PVC',	applicationIdList : [1,2,3,4],	applicationList : ['Bedroom','living room','study room','dinning room'],	},
{	popular : '',	productId : 'ertm001',	productName : 'Non-woven wall paper 3d effect',	categoryId : '3',	length : '53',	width : '1000',	effectId : '1',	materialId : '4',		categoryName : 'wall paper',	effectName : '3D',	materialName : 'Non-woven paper',	applicationIdList : [1,2],	applicationList : ['Bedroom','living room'],	},
{	popular : '',	productId : 'ertm002',	productName : 'Self-adhesive green board sticker',	categoryId : '3',	length : '45',	width : '200',	effectId : '',	materialId : '2',		categoryName : 'wall paper',	effectName : '',	materialName : 'PVC',	applicationIdList : [3,6],	applicationList : ['study room','commerical area'],	},
{	popular : '',	productId : 'ertm002',	productName : 'Self-adhesive white board sticker',	categoryId : '3',	length : '45',	width : '200',	effectId : '',	materialId : '2',		categoryName : 'wall paper',	effectName : '',	materialName : 'PVC',	applicationIdList : [3,6],	applicationList : ['study room','commerical area'],	},

];

ez.data.products = productData;

    categoryList = ["Wall Hangings", "Wall Decals", "Wall Papers"];
    ez.data.categoryList = categoryList;

    applicationList = ["Bedroom", "Living room", "Study room", "Dining room", "Nursery room", "Commerical area"];
    ez.data.applicationList = applicationList;
})()
/* Test Data End */
